blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://community.sourcify.io
    about: Suggest an idea for this project
  - name: Question / Problem
    url: https://community.sourcify.io
    about: Questions and problems with sourcify
