import type { PluginObject } from 'vue';
import sourcifyActionBox from '../components/sourcifyActionBox';
import sourcifyActionDropdown from '../components/sourcifyActionDropdown';
import sourcifyActionToggle from '../components/sourcifyActionToggle';
import sourcifyAlert from '../components/sourcifyAlert';
import sourcifyAvatar from '../components/sourcifyAvatar';
import sourcifyBadge from '../components/sourcifyBadge';
import sourcifyBlockUi from '../components/sourcifyBlockUi';
import sourcifyButton from '../components/sourcifyButton';
import { sourcifyElButton } from '../components/sourcifyButton/overrides';
import sourcifyCallout from '../components/sourcifyCallout';
import sourcifyCard from '../components/sourcifyCard';
import sourcifyDatatable from '../components/sourcifyDatatable';
import sourcifyFormBox from '../components/sourcifyFormBox';
import sourcifyFormInputs from '../components/sourcifyFormInputs';
import sourcifyFormInput from '../components/sourcifyFormInput';
import sourcifyHeading from '../components/sourcifyHeading';
import sourcifyIcon from '../components/sourcifyIcon';
import sourcifyIconButton from '../components/sourcifyIconButton';
import sourcifyInfoAccordion from '../components/sourcifyInfoAccordion';
import sourcifyInfoTip from '../components/sourcifyInfoTip';
import { default as sourcifyInput } from '../components/sourcifyInput';
import sourcifyInputLabel from '../components/sourcifyInputLabel';
import sourcifyInputNumber from '../components/sourcifyInputNumber';
import sourcifyLink from '../components/sourcifyLink';
import sourcifyLoading from '../components/sourcifyLoading';
import sourcifyMarkdown from '../components/sourcifyMarkdown';
import sourcifyMenu from '../components/sourcifyMenu';
import sourcifyMenuItem from '../components/sourcifyMenuItem';
import sourcifyNodeCreatorNode from '../components/sourcifyNodeCreatorNode';
import sourcifyNodeIcon from '../components/sourcifyNodeIcon';
import sourcifyNotice from '../components/sourcifyNotice';
import sourcifyOption from '../components/sourcifyOption';
import sourcifyPopover from '../components/sourcifyPopover';
import sourcifyPulse from '../components/sourcifyPulse';
import sourcifyRadioButtons from '../components/sourcifyRadioButtons';
import sourcifySelect from '../components/sourcifySelect';
import sourcifySpinner from '../components/sourcifySpinner';
import sourcifySticky from '../components/sourcifySticky';
import sourcifyTabs from '../components/sourcifyTabs';
import sourcifyTag from '../components/sourcifyTag';
import sourcifyTags from '../components/sourcifyTags';
import sourcifyText from '../components/sourcifyText';
import sourcifyTooltip from '../components/sourcifyTooltip';
import sourcifyTree from '../components/sourcifyTree';
import sourcifyUserInfo from '../components/sourcifyUserInfo';
import sourcifyUserSelect from '../components/sourcifyUserSelect';
import sourcifyUsersList from '../components/sourcifyUsersList';
import sourcifyResizeWrapper from '../components/sourcifyResizeWrapper';
import sourcifyRecycleScroller from '../components/sourcifyRecycleScroller';

const sourcifyComponentsPlugin: PluginObject<{}> = {
	install: (app) => {
		app.component('sourcify-info-accordion', sourcifyInfoAccordion);
		app.component('sourcify-action-box', sourcifyActionBox);
		app.component('sourcify-action-dropdown', sourcifyActionDropdown);
		app.component('sourcify-action-toggle', sourcifyActionToggle);
		app.component('sourcify-alert', sourcifyAlert);
		app.component('sourcify-avatar', sourcifyAvatar);
		app.component('sourcify-badge', sourcifyBadge);
		app.component('sourcify-block-ui', sourcifyBlockUi);
		app.component('sourcify-button', sourcifyButton);
		app.component('el-button', sourcifyElButton);
		app.component('sourcify-callout', sourcifyCallout);
		app.component('sourcify-card', sourcifyCard);
		app.component('sourcify-datatable', sourcifyDatatable);
		app.component('sourcify-form-box', sourcifyFormBox);
		app.component('sourcify-form-inputs', sourcifyFormInputs);
		app.component('sourcify-form-input', sourcifyFormInput);
		app.component('sourcify-icon', sourcifyIcon);
		app.component('sourcify-icon-button', sourcifyIconButton);
		app.component('sourcify-info-tip', sourcifyInfoTip);
		app.component('sourcify-input', sourcifyInput);
		app.component('sourcify-input-label', sourcifyInputLabel);
		app.component('sourcify-input-number', sourcifyInputNumber);
		app.component('sourcify-loading', sourcifyLoading);
		app.component('sourcify-heading', sourcifyHeading);
		app.component('sourcify-link', sourcifyLink);
		app.component('sourcify-markdown', sourcifyMarkdown);
		app.component('sourcify-menu', sourcifyMenu);
		app.component('sourcify-menu-item', sourcifyMenuItem);
		app.component('sourcify-node-creator-node', sourcifyNodeCreatorNode);
		app.component('sourcify-node-icon', sourcifyNodeIcon);
		app.component('sourcify-notice', sourcifyNotice);
		app.component('sourcify-option', sourcifyOption);
		app.component('sourcify-popover', sourcifyPopover);
		app.component('sourcify-pulse', sourcifyPulse);
		app.component('sourcify-select', sourcifySelect);
		app.component('sourcify-spinner', sourcifySpinner);
		app.component('sourcify-sticky', sourcifySticky);
		app.component('sourcify-radio-buttons', sourcifyRadioButtons);
		app.component('sourcify-tags', sourcifyTags);
		app.component('sourcify-tabs', sourcifyTabs);
		app.component('sourcify-tag', sourcifyTag);
		app.component('sourcify-text', sourcifyText);
		app.component('sourcify-tooltip', sourcifyTooltip);
		app.component('sourcify-user-info', sourcifyUserInfo);
		app.component('sourcify-tree', sourcifyTree);
		app.component('sourcify-users-list', sourcifyUsersList);
		app.component('sourcify-user-select', sourcifyUserSelect);
		app.component('sourcify-resize-wrapper', sourcifyResizeWrapper);
		app.component('sourcify-recycle-scroller', sourcifyRecycleScroller);
	},
};

export default sourcifyComponentsPlugin;
