name: Check Documentation URLs

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-docs-urls:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build nodes-base
        run: pnpm --filter sourcify-workflow --filter=sourcify-core --filter=sourcify-nodes-base build

      - name: Test URLS
        run: node scripts/validate-docs-links.js

      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          channel: '#updates-build-alerts'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: Documentation URLs check failed (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
